use_frameworks!

platform :ios, '10.0'

target 'KKDeviceInsightKit_Example' do
  pod 'KKDeviceInsightKit', :path => '../'

  target 'KKDeviceInsightKit_Tests' do
    inherit! :search_paths

    
  end
end
